
  CREATE TABLE "ADDRESS" 
   (	"ADD_ID" NUMBER, 
	"COUNTRY" VARCHAR2(255), 
	"STATE" VARCHAR2(255), 
	"CITY" VARCHAR2(255), 
	"STREET" VARCHAR2(255), 
	"ZIPCODE" NUMBER, 
	"PRE_KNOWN_ADD" CLOB, 
	"CREATED_TS" TIMESTAMP (6), 
	"LAST_UPDATED_TS" TIMESTAMP (6), 
	 PRIMARY KEY ("ADD_ID")
  USING INDEX  ENABLE
   ) ;